.changeset/flat-dodos-compete.md
packages/sif-common-sentry/src/index.ts

Ikke feile dersom headers er undefined under logApiCallErrorToSentryOrConsole

Sentry bugfix

---

.changeset/slimy-balloons-flow.md
apps/app-template/src/app/App.tsx
apps/endringsmelding-psb/src/app/App.tsx
apps/omsorgspengesoknad/src/app/App.tsx
apps/sif-ettersending/src/app/App.tsx
packages/sif-common-soknad-ds/src/index.ts
packages/sif-common-soknad-ds/src/utils/ensureBaseNameForReactRouter.ts

Util for å redirecte bruker til publicPath for app, dersom en kommer til root

Ensure base name for react router

---

.changeset/chilled-plums-tan.md
.changeset/eight-numbers-type.md
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/omsorgspengesoknad/src/app/søknad/steps/oppsummering/VedleggOppsummering.tsx
apps/omsorgspengesoknad/src/app/utils/søknadsdataToApiData/getApiDataFromSøknadsdata.ts
packages/sif-common-soknad-ds/CHANGELOG.md
packages/sif-common-soknad-ds/package.json

Oppsummeringen listet ikke opp vedlegg.

Bugfix - omsorgspengesøknad oppsummering

---

.changeset/long-doors-cross.md
apps/omsorgspengesoknad/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx

harBekreftetOpplysninger ble ikke satt ved innsending. Feil oppstod etter tilpasning til typescript5

Fikse harBekreftetOpplysninger bug

---

apps/endringsmelding-pleiepenger/.storybook/main.js
apps/omsorgspengesoknad/.storybook/main.js
packages/sif-common-core-ds/.storybook/main.js
packages/sif-common-formik-ds/.storybook/main.js
packages/sif-common-forms-ds/.storybook/main.js
packages/sif-common-soknad-ds/.storybook/main.js

https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/78#issuecomment-1409224863

Midlertidig fix før storybook7 oppgradering

---

.changeset/lazy-bees-approve.md
apps/omsorgspengesoknad/src/app/søknad/SøknadRouter.tsx

Fange opp ugyldig tilstand i velkommen-søknadsdata

Omsorgspengesoknad

---

.github/workflows/dispatch.deploy-ekstra-omsorgsdager-andre-forelder-ikke-tilsyn-to-prod.yml
.github/workflows/dispatch.deploy-endringsmelding-pleiepenger-to-prod.yml
.github/workflows/dispatch.deploy-ettersending-to-prod.yml
.github/workflows/dispatch.deploy-omsorgsdager-aleneomsorg-dialog-to-prod.yml
.github/workflows/dispatch.deploy-omsorgspengesøknad-to-prod.yml
.github/workflows/dispatch.deploy-to-dev.yml

Legge til autodeploy til prod ved endringer i endringsmelding på main-branchen.

Oppdatere workflow for endringsmelding

---

.changeset/modern-ladybugs-deliver.md
apps/pleiepenger-sykt-barn/src/app/i18n/nb.json
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidssituasjon-step/components/frilans-form-parts/FrilanserFormPart.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidssituasjon-step/components/frilans-form-parts/spørsmål/FrilansNormalarbeidstidSpørsmål.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidssituasjon-step/components/frilans-form-parts/spørsmål/HarHattInntektSomFrilanserSpørsmål.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidssituasjon-step/components/info/InfoArbeiderNormaltTimerIUken.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidstid-step/ArbeidstidStep.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidstid-step/components/ArbeidstidFrilans.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidstid-step/components/info/ArbeidIPeriodeInfo.tsx
apps/pleiepenger-sykt-barn/src/app/søknad/arbeidstid-step/i18n/arbeidIPeriodeMessages.ts

Justere tekst rundt fosterhjemsgodtgjørelse eller omsorgsstønad.

Tekstoppdatering PSB

---

.github/workflows/.deploy-app-to-dev.yml

GHCR er deprecated og skal erstattes av GAR

Migreret deploy-dev workflow til GAR.

---

.github/workflows/dispatch.deploy-to-dev.yml

id-token write in dispatch.deploy-to-dev.yml

---

.changeset/orange-crews-yell.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/CHANGELOG.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/package.json
apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/omsorgsdager-aleneomsorg-dialog/CHANGELOG.md
apps/omsorgsdager-aleneomsorg-dialog/package.json
apps/omsorgspengerutbetaling-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/pleiepenger-i-livets-sluttfase-soknad/CHANGELOG.md
apps/pleiepenger-i-livets-sluttfase-soknad/package.json
apps/pleiepenger-sykt-barn/CHANGELOG.md
apps/pleiepenger-sykt-barn/package.json
apps/sif-ettersending/CHANGELOG.md
apps/sif-ettersending/package.json
packages/sif-common-formik-ds/CHANGELOG.md
packages/sif-common-formik-ds/package.json
packages/sif-common-formik-ds/src/components/formik-date-range-picker/dateRangePickerUtils.ts
packages/sif-common-formik-ds/storybook/stories/components/FormikDateRangePicker.stories.tsx
packages/sif-common-ui/CHANGELOG.md
packages/sif-common-ui/package.json

Feilfiks når maks og min dato er på samme dag. Da ble undefined returnert, noe som igjen førte til at dropdownCaption ikke virket som forventet. Nå returneres alltid en min eller maks dato dersom dette er satt.

Datepicker min max fix

---

apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/index.html
apps/endringsmelding-pleiepenger/e2e/server/mock-decorator.html
apps/endringsmelding-pleiepenger/heroku/index.html
apps/endringsmelding-pleiepenger/index.html
apps/omsorgsdager-aleneomsorg-dialog/index.html
apps/omsorgspengerutbetaling-soknad/index.html
apps/omsorgspengesoknad/e2e/server/mock-decorator.html
apps/omsorgspengesoknad/index.html
apps/pleiepenger-i-livets-sluttfase-soknad/index.html
apps/pleiepenger-sykt-barn/index.html
apps/sif-ettersending/e2e/server/mock-decorator.html
apps/sif-ettersending/index.html

Ulike justeringer etter uu-gjennomgang

Legge til charSet i head

---

apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/omsorgsdager-aleneomsorg-dialog/CHANGELOG.md
apps/omsorgsdager-aleneomsorg-dialog/package.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-arbeidstaker-soknad/package.json
apps/omsorgspengerutbetaling-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/pleiepenger-i-livets-sluttfase-soknad/CHANGELOG.md
apps/pleiepenger-i-livets-sluttfase-soknad/package.json
apps/pleiepenger-sykt-barn/CHANGELOG.md
apps/pleiepenger-sykt-barn/package.json
packages/sif-common-forms-ds/CHANGELOG.md
packages/sif-common-forms-ds/package.json

Legge til manglende changeset for endring i sif-common-forms

Oppdatere versjonsnr av sif-comon-forms-ds

---

apps/dine-pleiepenger/src/pages/index.page.tsx
apps/dine-pleiepenger/src/server/api-models/SøknadSchema.ts
apps/dine-pleiepenger/src/server/apiService.ts
apps/dine-pleiepenger/src/utils/søknadUtils.ts

Logge perioder og type søknader i dine pleiepenger.

---

apps/endringsmelding-pleiepenger/src/app/api/endpoints/sakerEndpoint.ts

Utvide log i endringsmelding

---

.changeset/tough-turkeys-compare.md
apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/endringsmelding-pleiepenger/src/app/pages/ingen-tilgang/IngenTilgangPage.tsx

Endre tekst på melding som møter bruker når vi ikke finner en sak.

Tekstoppdatering - ingen sak melding

---

apps/endringsmelding-pleiepenger/src/app/api/endpoints/sakerEndpoint.ts
apps/endringsmelding-pleiepenger/src/app/api/fetchInitialData.ts

Fjerne midlertidig ekstra logging.

Fjerne temp logInfo

---

apps/omsorgsdager-kalkulator/package.json
yarn.lock

På grunn av endringer i config som ikke var gjort i forrige merge.

Set eslint til 8.56.0

---

.changeset/gold-points-develop.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/CHANGELOG.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/package.json
apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/omsorgsdager-aleneomsorg-dialog/CHANGELOG.md
apps/omsorgsdager-aleneomsorg-dialog/package.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-arbeidstaker-soknad/package.json
apps/omsorgspengerutbetaling-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/pleiepenger-i-livets-sluttfase-soknad/CHANGELOG.md
apps/pleiepenger-i-livets-sluttfase-soknad/package.json
apps/pleiepenger-sykt-barn/CHANGELOG.md
apps/pleiepenger-sykt-barn/package.json
apps/sif-ettersending/CHANGELOG.md
apps/sif-ettersending/package.json
packages/sif-common-core-ds/CHANGELOG.md
packages/sif-common-core-ds/package.json
packages/sif-common-formik-ds/src/validation/getFødselsnummerValidator.ts
packages/sif-common-ui/CHANGELOG.md
packages/sif-common-ui/package.json
yarn.lock

Den feilet lokalt ved import fnrvalidator from ..., men fungerer ok med import { fnr } from ...

Endre hvordan en importerer @navikt/fnrvalidator

---

apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx
apps/endringsmelding-pleiepenger/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx
apps/omsorgsdager-aleneomsorg-dialog/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx
apps/omsorgspengerutbetaling-arbeidstaker-soknad/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx
apps/omsorgspengesoknad/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx
apps/pleiepenger-i-livets-sluttfase-soknad/src/app/søknad/steps/oppsummering/OppsummeringStep.tsx

Feilmelding var ikke wrappet i <ErrorSummaryItem/>

Korrigere Feilmeldingsboks for feil ved innsending

---

.changeset/chilly-baboons-fix.md
packages/sif-common-formik-ds/src/components/formik-datepicker/date-input-and-picker/DateInputAndPicker.tsx
packages/sif-common-formik-ds/src/components/formik-datepicker/date-input-and-picker/usePrevious.ts
packages/sif-common-formik-ds/storybook/stories/components/FormikDatePicker.stories.tsx

Bugfix. Verdi i input ble ikke oppdatert dersom en satte value på datepicker programmatisk. Dette er nå mulig.

Bugfix datepicker

---

apps/dine-pleiepenger/api-mock-server/mockdata/saker.json
apps/dine-pleiepenger/src/utils/zodUtils.ts

- Legge til recursiv kall for child-issues
- Oppdater saker - mock (trengs ikke sees på)

Utvide logging når en får zod-valideringsfeil

---

.changeset/serious-bottles-vanish.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/src/app/søknad/steps/annen-forelderens-situasjon/AnnenForelderenSituasjonStep.tsx
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/src/app/søknad/steps/annen-forelderens-situasjon/annenForelderenSituasjonMessages.ts

Legge til melding når bruker velger annet, + fjerne tekst om at bruker allikevel kan fortsette.

Vise melding når annen forelders situasjon er "Annet"

---

.changeset/great-parents-agree.md
.changeset/serious-bottles-vanish.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/CHANGELOG.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/omsorgspengesoknad/src/app/søknad/steps/om-barnet/stegOmBarnetMessages.ts

Tekstendring - omsorgspengesøknad

---

apps/dine-pleiepenger/api-mock-server/api-mock-server.js
apps/dine-pleiepenger/api-mock-server/mockdata/saker-ettersendelse-case.json
apps/dine-pleiepenger/src/utils/__tests__/sakUtils.test.ts
apps/dine-pleiepenger/src/utils/sakUtils.ts

Skjuler vedtak-hendelse i tidslinjen for en behandling hvis behandlingen kun inneholder ettersendelse.

Skjule vedtak/fremtidig vedtak ved beh med kun ettersendelse

---

apps/dine-pleiepenger/api-mock-server/api-mock-server.js
apps/dine-pleiepenger/api-mock-server/mockdata/saker.json
apps/dine-pleiepenger/src/server/apiService.ts

Noen innsendelser blir klassifisert som UKJENT. Vi klarer ikke vise disse, så denne PR'en filtrerer bort disse fra saker vi henter opp.

Filtrere bort innsendelsestype===UKJENT

---

apps/omsorgsdager-aleneomsorg-dialog/src/app/pages/velkommen/velkommenPageMessages.ts

Denne endringen forenkler velkommen-meldingen i søknaden for aleneomsorg. Det var noen ting i denne teksten som ikke stemte for denne søknaden.

Forenkle velkommen-meldingen

---

apps/pleiepenger-sykt-barn/nais/dev-gcp.json
apps/pleiepenger-sykt-barn/nais/prod-gcp.json

Amplitude events ble ikke logget i PSB

Bugfix - USE_AMPLITUDE

---

.changeset/gold-years-smoke.md
.changeset/proud-fans-cover.md
.changeset/swift-sheep-deliver.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/CHANGELOG.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/package.json
apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/omsorgsdager-aleneomsorg-dialog/CHANGELOG.md
apps/omsorgsdager-aleneomsorg-dialog/package.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-arbeidstaker-soknad/package.json
apps/omsorgspengerutbetaling-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/pleiepenger-i-livets-sluttfase-soknad/CHANGELOG.md
apps/pleiepenger-i-livets-sluttfase-soknad/package.json
apps/pleiepenger-sykt-barn/CHANGELOG.md
apps/pleiepenger-sykt-barn/package.json
apps/sif-ettersending/CHANGELOG.md
apps/sif-ettersending/package.json
packages/sif-common-formik-ds/CHANGELOG.md
packages/sif-common-formik-ds/package.json
packages/sif-common-soknad-ds/CHANGELOG.md
packages/sif-common-soknad-ds/package.json
packages/sif-common-ui/CHANGELOG.md
packages/sif-common-ui/package.json
yarn.lock

Oppdatere versjonsnumre slik at alle applikasjoner blir oppdatert i prod med FormProgress komponent fra Aksel.

Progress stepper

---

apps/dine-pleiepenger/nais/dev-gcp.json
apps/dine-pleiepenger/nais/prod-gcp.json
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/nais/dev-gcp.json
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/nais/prod-gcp.json
apps/endringsmelding-pleiepenger/nais/dev-gcp.json
apps/endringsmelding-pleiepenger/nais/prod-gcp.json
apps/omsorgsdager-aleneomsorg-dialog/nais/dev-gcp.json
apps/omsorgsdager-aleneomsorg-dialog/nais/prod-gcp.json
apps/omsorgsdager-kalkulator/nais/dev-gcp.json
apps/omsorgsdager-kalkulator/nais/prod-gcp.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/nais/dev-gcp.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/nais/prod-gcp.json
apps/omsorgspengerutbetaling-soknad/nais/dev-gcp.json
apps/omsorgspengerutbetaling-soknad/nais/prod-gcp.json
apps/omsorgspengesoknad/nais/dev-gcp.json
apps/omsorgspengesoknad/nais/prod-gcp.json
apps/pleiepenger-i-livets-sluttfase-soknad/nais/dev-gcp.json
apps/pleiepenger-i-livets-sluttfase-soknad/nais/prod-gcp.json
apps/pleiepenger-sykt-barn/nais/dev-gcp.json
apps/pleiepenger-sykt-barn/nais/prod-gcp.json
apps/sif-ettersending/nais/dev-gcp.json
apps/sif-ettersending/nais/prod-gcp.json
nais-config/nais.yml

Togglet av i prod-gcp enn så lenge.

Legger på opentelemtry auto instrumentation.

---

apps/dine-pleiepenger/package.json
apps/omsorgspengerutbetaling-soknad/package.json
packages/sif-common-core-ds/package.json
packages/sif-common-ui/package.json
yarn.lock

Vi bruker ikke chromatic aktivt nå, så da fjernes scripta fra reopet

Fjerne chromatic - ikke aktivt brukt

---

apps/omsorgspengerutbetaling-soknad/e2e/playwright/tests/fyll-ut-søknad.spec.ts
apps/omsorgspengerutbetaling-soknad/e2e/playwright/tests/test-dine-barn.spec.ts
apps/omsorgspengerutbetaling-soknad/e2e/playwright/utils/setNow.ts
apps/omsorgspengerutbetaling-soknad/e2e/playwright/utils/utfyllingUtils.ts
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengerutbetaling-soknad/playwright.config.ts
apps/omsorgspengerutbetaling-soknad/src/app/App.tsx
apps/omsorgspengerutbetaling-soknad/src/build/AppSettings.cjs
yarn.lock

Overstyrer Date.now i tester, slik at utfylling går greit.

Setter mockDato for at PW-tester skal kjøre

---

apps/omsorgsdager-aleneomsorg-dialog/nais/dev-gcp.json
apps/omsorgsdager-aleneomsorg-dialog/nais/prod-gcp.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/nais/dev-gcp.json
apps/omsorgspengerutbetaling-arbeidstaker-soknad/nais/prod-gcp.json
apps/omsorgspengerutbetaling-soknad/nais/dev-gcp.json
apps/omsorgspengerutbetaling-soknad/nais/prod-gcp.json

Fikser login issue i dev for dekoratøren

Legge til ENV i nais filer 

---

apps/pleiepenger-sykt-barn/src/app/i18n/appMessages.ts
apps/pleiepenger-sykt-barn/src/app/søknad/tidsrom-step/TidsromStep.tsx
apps/pleiepenger-sykt-barn/src/app/validation/__tests__/fieldValidations.test.ts
apps/pleiepenger-sykt-barn/src/app/validation/fieldValidations.ts

https://jira.adeo.no/browse/TSFF-865

Sette maks periode til ett år frem i tid

---

apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/dev-server.cjs
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/nais/prod-gcp.json
apps/endringsmelding-pleiepenger/dev-server.cjs
apps/endringsmelding-pleiepenger/nais/dev-gcp.json
apps/endringsmelding-pleiepenger/nais/prod-gcp.json
apps/omsorgsdager-aleneomsorg-dialog/dev-server.cjs
apps/omsorgspengerutbetaling-arbeidstaker-soknad/dev-server.cjs
apps/omsorgspengerutbetaling-soknad/dev-server.cjs
apps/omsorgspengesoknad/dev-server.cjs
apps/omsorgspengesoknad/nais/dev-gcp.json
apps/omsorgspengesoknad/nais/prod-gcp.json
apps/pleiepenger-i-livets-sluttfase-soknad/dev-server.cjs
apps/pleiepenger-i-livets-sluttfase-soknad/nais/prod-gcp.json
apps/pleiepenger-sykt-barn/dev-server.cjs
apps/pleiepenger-sykt-barn/nais/dev-gcp.json
apps/sif-demo-app/dev-server.cjs
apps/sif-ettersending/dev-server.cjs
apps/ungdomsytelse-soknad/dev-server.cjs
apps/ungdomsytelse-veileder/dev-server.cjs

- Setter env til localhost i dekoratøren i dev-server, slik at amplitude ikke aktiveres.
- Rydde i prod-gcp og dev-gcp slik at alle setter ENV variabelen

Rydde i ENV environmentvariabel

---

apps/ungdomsytelse-deltaker/api-mock/mock-server.cjs
apps/ungdomsytelse-deltaker/src/api/schemas/deltakelseSchema.ts
apps/ungdomsytelse-deltaker/src/api/schemas/deltakelserSchema.ts
apps/ungdomsytelse-deltaker/src/api/schemas/søknadApiDataSchema.ts
apps/ungdomsytelse-deltaker/src/api/services/deltakerService.ts
apps/ungdomsytelse-deltaker/src/api/types/index.ts
apps/ungdomsytelse-deltaker/src/components/deltakelse-table/DeltakelseTable.tsx
apps/ungdomsytelse-deltaker/src/components/inntektsrapportering/InnteksrapporteringForm.tsx
apps/ungdomsytelse-deltaker/src/components/inntektsrapportering/InntektEnMånedForm.tsx
apps/ungdomsytelse-deltaker/src/components/inntektsrapportering/Inntektsrapportering.tsx
apps/ungdomsytelse-deltaker/src/hooks/useInitialData.ts
apps/ungdomsytelse-deltaker/src/hooks/useRapporterInntekt.ts
apps/ungdomsytelse-deltaker/src/søknad/Søknad.tsx
apps/ungdomsytelse-deltaker/src/søknad/context/SøknadContext.tsx
apps/ungdomsytelse-deltaker/src/søknad/form/DeltakelseForm.tsx
apps/ungdomsytelse-deltaker/src/søknad/form/Forside.tsx
apps/ungdomsytelse-deltaker/src/søknad/hooks/useSendSøknad.ts
apps/ungdomsytelse-deltaker/src/utils/deltakelserUtils.ts

Bruke perioder som hentes ut fra backend.

Ung rapporteringsperioder

---

apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/CHANGELOG.md
apps/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/package.json
apps/endringsmelding-pleiepenger/CHANGELOG.md
apps/endringsmelding-pleiepenger/package.json
apps/omsorgsdager-aleneomsorg-dialog/CHANGELOG.md
apps/omsorgsdager-aleneomsorg-dialog/package.json
apps/omsorgsdager-kalkulator/CHANGELOG.md
apps/omsorgsdager-kalkulator/package.json
apps/omsorgspengerutbetaling-soknad/CHANGELOG.md
apps/omsorgspengerutbetaling-soknad/package.json
apps/omsorgspengesoknad/CHANGELOG.md
apps/omsorgspengesoknad/package.json
apps/pleiepenger-i-livets-sluttfase-soknad/CHANGELOG.md
apps/pleiepenger-i-livets-sluttfase-soknad/package.json
apps/pleiepenger-sykt-barn/CHANGELOG.md
apps/pleiepenger-sykt-barn/package.json
apps/sif-ettersending/CHANGELOG.md
apps/sif-ettersending/package.json
packages/sif-common-core-ds/storybook/stories/components/FormikFileUpload.stories.tsx
packages/sif-common-formik-ds/CHANGELOG.md
packages/sif-common-formik-ds/package.json
packages/sif-common-formik-ds/src/components/helpers/ValidationSummary.tsx

Fiks bug ved klikk på feilmelding i ValidationSummary

Formik file upload

---

apps/pleiepenger-sykt-barn/mock/mock-api-server.cjs

Dev-fix - psb mock data

---

apps/pleiepenger-i-livets-sluttfase-soknad/.env.example
apps/pleiepenger-i-livets-sluttfase-soknad/.storybook/preview-head.html
apps/pleiepenger-i-livets-sluttfase-soknad/e2e/playwright/playwright.env.ts
apps/pleiepenger-i-livets-sluttfase-soknad/env.schema.ts
apps/pleiepenger-i-livets-sluttfase-soknad/nais/dev-gcp.json
apps/pleiepenger-i-livets-sluttfase-soknad/nais/prod-gcp.json
apps/pleiepenger-i-livets-sluttfase-soknad/src/app/utils/appEnv.ts
apps/pleiepenger-i-livets-sluttfase-soknad/src/app/utils/getTilgjengeligSøknadsperiode.ts

Featuretoggle - Søke ett år tilbake i tid

---

packages/sif-common-formik-ds/storybook/decorators/StoryFormikWrapper.tsx
packages/sif-common-formik-ds/storybook/stories/components/FormikTextarea.stories.tsx

Legge til manglende IntlProvider

Storybook oppdatering

---

apps/endringsmelding-pleiepenger/src/app/i18n/appMessages.ts
apps/endringsmelding-pleiepenger/src/app/lenker.tsx
apps/endringsmelding-pleiepenger/src/app/pages/ingen-tilgang/IngenTilgangPage.stories.tsx
apps/endringsmelding-pleiepenger/src/app/pages/ingen-tilgang/IngenTilgangPage.tsx
apps/endringsmelding-pleiepenger/src/app/utils/__tests__/tilgangskontroll.test.ts

Endring pga et skille på disse to tjenestene på nav.no

Endre til Send beskjed i stedet for Skriv til oss der det er riktig i endringsmelding

---

apps/omsorgsdager-kalkulator/components/section-panel/sectionPanel.scss
apps/omsorgsdager-kalkulator/pages/_document.tsx

Bugfix på å sette riktig css layer-rekkefølge.

Fix layer rekkefølge

---

apps/ungdomsytelse-deltaker/src/utils/initApiClients.ts
packages/ung-common/src/api/index.ts
packages/ung-common/src/api/k9BrukerdialogProsesseringUngdomsytelseApiClient.ts

Fix initialisering av api client

Fix initClient
